#
# GRAKN.AI - THE KNOWLEDGE GRAPH
# Copyright (C) 2019 Grakn Labs Ltd
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

version: 2.1
commands:
  install-bazel:
    steps:
      - run: curl -OL https://raw.githubusercontent.com/graknlabs/dependencies/master/tool/bazelinstall/linux.sh
      - run: bash ./linux.sh && rm ./linux.sh
      - run: curl -OL https://raw.githubusercontent.com/graknlabs/dependencies/master/tool/bazelinstall/rbe.sh
      - run: bash ./rbe.sh && rm ./rbe.sh

  run-bazel:
    parameters:
      command:
          type: string
    steps:
      - run:
          command: bazel run @graknlabs_dependencies//tool/bazelrun:rbe -- << parameters.command >>
          no_output_timeout: 120m

  run-grakn:
    steps:
      - run-bazel:
          command: bazel run //:grakn-extractor -- dist/grakn-core-all-linux
      - run: nohup ./dist/grakn-core-all-linux/grakn server start

jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    working_directory: ~/examples
    steps:
      - install-bazel
      - checkout
      - run-bazel:
          command: bazel build //...
      - run:
          name: Verify dependencies/maven/artifacts.snapshot
          command: |
            dependencies/maven/update.sh
            git diff --exit-code dependencies/maven/artifacts.snapshot
      - run:
          command: bazel run @graknlabs_dependencies//tool/unuseddeps:unused-deps -- list
          no_output_timeout: 30m


  test-phone-calls-java:
    machine:
      image: ubuntu-1604:201903-01
    working_directory: ~/examples
    steps:
      - install-bazel
      - checkout
      - run-grakn
      - run: bazel test //phone_calls/java:test --test_output=errors


  test-phone-calls-nodejs:
    machine:
      image: ubuntu-1604:201903-01
    working_directory: ~/examples
    steps:
      - install-bazel
      - checkout
      - run-grakn
      - run: sleep 60
      - run: bazel test //phone_calls/nodejs:test --test_output=errors

  test-phone-calls-python:
    machine:
      image: ubuntu-1604:201903-01
    working_directory: ~/examples
    steps:
      - install-bazel
      - checkout
      - run-grakn
      - run: bazel test //phone_calls/python:test --test_output=errors

  test-tube-network:
    machine:
      image: ubuntu-1604:201903-01
    working_directory: ~/examples
    steps:
      - install-bazel
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install python3-tk tk-dev  # Required for tkinter
      - run: pyenv install 3.6.3
      - run: pyenv global 3.6.3 2.7.12
      - run-grakn
      - run:
          name: "Run test with a virtual X-server running"
          command: |
            Xvfb :0 -screen 0 1024x768x24 &
            bazel test //tube_network:test --test_output=errors --python_version PY3 --python_path $(which python) --action_env=DISPLAY=":0"
      - run: bazel test //tube_network:test-migration --test_output=errors --python_version PY3 --python_path $(which python)

workflows:
  examples:
    jobs:
      - build
      - test-phone-calls-java
      - test-phone-calls-nodejs
      - test-phone-calls-python
      - test-tube-network
